### ISSUE TITLE
Crashes upon starting up a game

### ISSUE THREAD

**Issue by DerRoboMeister** [LXGaming/MixinBootstrap#1]
This is what I got from the game output log - no error log could be provided, tho. I should also note that I uninstalled every other mod except for Kottle, a fork of Kotlin, and Better Foliage, a mod that requires this library

Preparing to launch minecraft client for 1.14.4-forge-28.1.0
16:31:28.827
Prepared asset index
16:31:28.843
Have 2076 total files to check or download
16:31:28.846
Waiting for 2076 futures
16:31:29.019
Checking installations.
16:31:29.019
Minecraft client 1.14.4-forge-28.1.0 is ready to start.
16:31:29.019
Starting!
16:31:29.019
Nothing to download!
16:31:29.019
Extracting 7 files!
16:31:29.090
Version does not support log configuration, will assume one plaintext entry per line
16:31:29.090
Installing versions!
16:31:29.569
2020-01-18 16:31:29,568 main WARN Advanced terminal features are not available in this environment
16:31:29.640
[16:31:29] [main/INFO] [cp.mo.mo.Launcher/MODLAUNCHER]: ModLauncher running: args [--username, RoboTheMan, --version, 1.14.4-forge-28.1.0, --gameDir, C:\Users\samhu\OneDrive\Desktop\Minecraft Alt. Directories\1.14.4 Directory, --assetsDir, C:\Users\samhu\AppData\Roaming\.minecraft\assets, --assetIndex, 1.14, --uuid, 9371c166326c4d4cb4ddbb39cedc424c, --accessToken, ????????, --userType, mojang, --versionType, release, --launchTarget, fmlclient, --fml.forgeVersion, 28.1.0, --fml.mcVersion, 1.14.4, --fml.forgeGroup, net.minecraftforge, --fml.mcpVersion, 20190829.143755]
16:31:29.642
[16:31:29] [main/INFO] [cp.mo.mo.Launcher/MODLAUNCHER]: ModLauncher 3.2.0+60+b86c1d4 starting: java version 1.8.0_51 by Oracle Corporation
[16:31:29] [main/INFO] [op.OptiFineTransformationService/]: OptiFineTransformationService.onLoad
16:31:29.730
[16:31:29] [main/INFO] [op.OptiFineTransformationService/]: OptiFine ZIP file: C:\Users\samhu\OneDrive\Desktop\Minecraft Alt. Directories\1.14.4 Directory\mods\OptiFine_1.14.4_HD_U_F4_MOD.jar
16:31:29.793
[16:31:29] [main/INFO] [ne.mi.fm.lo.FixSSL/CORE]: Added Lets Encrypt root certificates as additional trust
16:31:29.813
[16:31:29] [main/INFO] [op.OptiFineTransformationService/]: OptiFineTransformationService.initialize
16:31:29.895
Exception in thread "main" [16:31:29] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: org.spongepowered.asm.service.ServiceNotAvailableError: No mixin host service is available. Services: INVALID[ModLauncher] and 1 other invalid services.
16:31:29.895
[16:31:29] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at org.spongepowered.asm.service.MixinService.initService(MixinService.java:159)
16:31:29.895
[16:31:29] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at org.spongepowered.asm.service.MixinService.getServiceInstance(MixinService.java:125)
16:31:29.896
[16:31:29] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at org.spongepowered.asm.service.MixinService.getService(MixinService.java:120)
16:31:29.896
[16:31:29] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at org.spongepowered.asm.launch.MixinBootstrap.<clinit>(MixinBootstrap.java:78)
16:31:29.898
[16:31:29] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at org.spongepowered.asm.launch.MixinTransformationService.initialize(MixinTransformationService.java:84)
16:31:29.898
[16:31:29] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at io.github.lxgaming.mixin.launch.MixinTransformationService.lambda$initialize$2(MixinTransformationService.java:82)
16:31:29.898
[16:31:29] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at io.github.lxgaming.mixin.launch.MixinTransformationService$$Lambda$144/1839337592.accept(Unknown Source)
16:31:29.898
[16:31:29] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at java.lang.Iterable.forEach(Iterable.java:75)
16:31:29.898
[16:31:29] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at io.github.lxgaming.mixin.launch.MixinTransformationService.initialize(MixinTransformationService.java:82)
16:31:29.898
[16:31:29] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at cpw.mods.modlauncher.TransformationServiceDecorator.onInitialize(TransformationServiceDecorator.java:67)
16:31:29.898
[16:31:29] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at cpw.mods.modlauncher.TransformationServicesHandler.lambda$initialiseTransformationServices$7(TransformationServicesHandler.java:106)
16:31:29.898
[16:31:29] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at cpw.mods.modlauncher.TransformationServicesHandler$$Lambda$86/989447607.accept(Unknown Source)
16:31:29.898
[16:31:29] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at java.util.HashMap$Values.forEach(HashMap.java:972)
16:31:29.899
[16:31:29] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at cpw.mods.modlauncher.TransformationServicesHandler.initialiseTransformationServices(TransformationServicesHandler.java:106)
16:31:29.904
[16:31:29] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at cpw.mods.modlauncher.TransformationServicesHandler.initializeTransformationServices(TransformationServicesHandler.java:59)
16:31:29.904
[16:31:29] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at cpw.mods.modlauncher.Launcher.run(Launcher.java:75)
16:31:29.904
[16:31:29] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at cpw.mods.modlauncher.Launcher.main(Launcher.java:65)
16:31:30.257
Process crashed with exit code 1

**Comment by LXGaming** [comment]
Update Forge to at least 28.1.45, I recommend just grabbing the latest build.

From the README:
> MinecraftForge must be running ModLauncher v4.1.0 or higher.
