### ISSUE TITLE
Crashing instantly on launch - MixinBootstrap v1.0.2

### ISSUE THREAD

**Issue by Huntifer** [LXGaming/MixinBootstrap#13]
<details>
<summary>debug.log</summary>

```
[22Apr2020 02:18:31.277] [main/INFO] [cpw.mods.modlauncher.Launcher/MODLAUNCHER]: ModLauncher running: args [--username, Huntifer, --version, 1.14.4-forge-28.1.0, --gameDir, C:\Users\chris\AppData\Roaming\.minecraft, --assetsDir, C:\Users\chris\AppData\Roaming\.minecraft\assets, --assetIndex, 1.14, --uuid, 150b9f916806422a93e27672d4a45d75, --accessToken, ????????, --userType, mojang, --versionType, release, --launchTarget, fmlclient, --fml.forgeVersion, 28.1.0, --fml.mcVersion, 1.14.4, --fml.forgeGroup, net.minecraftforge, --fml.mcpVersion, 20190829.143755]
[22Apr2020 02:18:31.280] [main/INFO] [cpw.mods.modlauncher.Launcher/MODLAUNCHER]: ModLauncher 3.2.0+60+b86c1d4 starting: java version 1.8.0_51 by Oracle Corporation
[22Apr2020 02:18:31.290] [main/DEBUG] [cpw.mods.modlauncher.LaunchServiceHandler/MODLAUNCHER]: Found launch services [minecraft,testharness,fmlclient,fmlserver]
[22Apr2020 02:18:31.298] [main/DEBUG] [cpw.mods.modlauncher.NameMappingServiceHandler/MODLAUNCHER]: Found naming services : []
[22Apr2020 02:18:31.306] [main/DEBUG] [cpw.mods.modlauncher.LaunchPluginHandler/MODLAUNCHER]: Found launch plugins: [eventbus,object_holder_definalize,runtime_enum_extender,accesstransformer,capability_inject_definalize,runtimedistcleaner]
[22Apr2020 02:18:31.313] [main/DEBUG] [cpw.mods.modlauncher.TransformationServicesHandler/MODLAUNCHER]: Discovering transformation services
[22Apr2020 02:18:31.330] [main/DEBUG] [cpw.mods.modlauncher.TransformationServicesHandler/MODLAUNCHER]: Found additional transformation services from discovery services: [C:\Users\chris\AppData\Roaming\.minecraft\mods\MixinBootstrap-1.0.0.jar, C:\Users\chris\AppData\Roaming\.minecraft\mods\OptiFine_1.14.4_HD_U_F5_MOD.jar]
[22Apr2020 02:18:31.371] [main/DEBUG] [cpw.mods.modlauncher.TransformationServicesHandler/MODLAUNCHER]: Found transformer services : [OptiFine,fml,mixinbootstrap]
[22Apr2020 02:18:31.371] [main/DEBUG] [cpw.mods.modlauncher.TransformationServicesHandler/MODLAUNCHER]: Transformation services loading
[22Apr2020 02:18:31.372] [main/DEBUG] [cpw.mods.modlauncher.TransformationServiceDecorator/MODLAUNCHER]: Loading service OptiFine
[22Apr2020 02:18:31.372] [main/INFO] [optifine.OptiFineTransformationService/]: OptiFineTransformationService.onLoad
[22Apr2020 02:18:31.373] [main/INFO] [optifine.OptiFineTransformationService/]: OptiFine ZIP file: C:\Users\chris\AppData\Roaming\.minecraft\mods\OptiFine_1.14.4_HD_U_F5_MOD.jar
[22Apr2020 02:18:31.379] [main/DEBUG] [cpw.mods.modlauncher.TransformationServiceDecorator/MODLAUNCHER]: Loaded service OptiFine
[22Apr2020 02:18:31.379] [main/DEBUG] [cpw.mods.modlauncher.TransformationServiceDecorator/MODLAUNCHER]: Loading service fml
[22Apr2020 02:18:31.380] [main/DEBUG] [net.minecraftforge.fml.loading.FMLServiceProvider/]: Injecting tracing printstreams for STDOUT/STDERR.
[22Apr2020 02:18:31.381] [main/DEBUG] [net.minecraftforge.fml.loading.LauncherVersion/CORE]: Found FMLLauncher version 28.1
[22Apr2020 02:18:31.381] [main/DEBUG] [net.minecraftforge.fml.loading.FMLLoader/CORE]: FML 28.1 loading
[22Apr2020 02:18:31.382] [main/DEBUG] [net.minecraftforge.fml.loading.FMLLoader/CORE]: FML found ModLauncher version : 3.2.0+60+b86c1d4
[22Apr2020 02:18:31.382] [main/DEBUG] [net.minecraftforge.fml.loading.FMLLoader/CORE]: Initializing modjar URL handler
[22Apr2020 02:18:31.382] [main/DEBUG] [net.minecraftforge.fml.loading.FMLLoader/CORE]: FML found AccessTransformer version : 1.0.0+45+b99295a
[22Apr2020 02:18:31.382] [main/DEBUG] [net.minecraftforge.fml.loading.FMLLoader/CORE]: FML found EventBus version : 1.0.0+54+3f83a9e
[22Apr2020 02:18:31.383] [main/DEBUG] [net.minecraftforge.fml.loading.FMLLoader/CORE]: Found Runtime Dist Cleaner
[22Apr2020 02:18:31.385] [main/DEBUG] [net.minecraftforge.fml.loading.FMLLoader/CORE]: FML found CoreMod version : 1.0.0+4+e6fed88
[22Apr2020 02:18:31.385] [main/DEBUG] [net.minecraftforge.fml.loading.FMLLoader/CORE]: Found ForgeSPI package implementation version 1.3.0+4+934b64a
[22Apr2020 02:18:31.385] [main/DEBUG] [net.minecraftforge.fml.loading.FMLLoader/CORE]: Found ForgeSPI package specification 3
[22Apr2020 02:18:31.436] [main/INFO] [net.minecraftforge.fml.loading.FixSSL/CORE]: Added Lets Encrypt root certificates as additional trust
[22Apr2020 02:18:31.437] [main/DEBUG] [cpw.mods.modlauncher.TransformationServiceDecorator/MODLAUNCHER]: Loaded service fml
[22Apr2020 02:18:31.437] [main/DEBUG] [cpw.mods.modlauncher.TransformationServiceDecorator/MODLAUNCHER]: Loading service mixinbootstrap
[22Apr2020 02:18:31.443] [main/DEBUG] [MixinBootstrap Launch/]: Registered MixinLaunchPlugin (mixin)
[22Apr2020 02:18:31.444] [main/DEBUG] [MixinBootstrap Launch/]: Registered MixinTransformationService (mixin)
[22Apr2020 02:18:31.444] [main/DEBUG] [MixinBootstrap Launch/]: Registered MixinLaunchPluginService (mixinbootstrap)
[22Apr2020 02:18:31.444] [main/DEBUG] [cpw.mods.modlauncher.TransformationServiceDecorator/MODLAUNCHER]: Loaded service mixinbootstrap
[22Apr2020 02:18:31.446] [main/DEBUG] [cpw.mods.modlauncher.TransformationServicesHandler/MODLAUNCHER]: Configuring option handling for services
[22Apr2020 02:18:31.453] [main/DEBUG] [cpw.mods.modlauncher.TransformationServicesHandler/MODLAUNCHER]: Transformation services initializing
[22Apr2020 02:18:31.453] [main/DEBUG] [cpw.mods.modlauncher.TransformationServiceDecorator/MODLAUNCHER]: Initializing transformation service OptiFine
[22Apr2020 02:18:31.453] [main/INFO] [optifine.OptiFineTransformationService/]: OptiFineTransformationService.initialize
[22Apr2020 02:18:31.453] [main/DEBUG] [cpw.mods.modlauncher.TransformationServiceDecorator/MODLAUNCHER]: Initialized transformation service OptiFine
[22Apr2020 02:18:31.453] [main/DEBUG] [cpw.mods.modlauncher.TransformationServiceDecorator/MODLAUNCHER]: Initializing transformation service fml
[22Apr2020 02:18:31.453] [main/DEBUG] [net.minecraftforge.fml.loading.FMLServiceProvider/CORE]: Setting up basic FML game directories
[22Apr2020 02:18:31.454] [main/DEBUG] [net.minecraftforge.fml.loading.FileUtils/CORE]: Found existing GAMEDIR directory : C:\Users\chris\AppData\Roaming\.minecraft
[22Apr2020 02:18:31.455] [main/DEBUG] [net.minecraftforge.fml.loading.FMLPaths/CORE]: Path GAMEDIR is C:\Users\chris\AppData\Roaming\.minecraft
[22Apr2020 02:18:31.455] [main/DEBUG] [net.minecraftforge.fml.loading.FileUtils/CORE]: Found existing MODSDIR directory : C:\Users\chris\AppData\Roaming\.minecraft\mods
[22Apr2020 02:18:31.455] [main/DEBUG] [net.minecraftforge.fml.loading.FMLPaths/CORE]: Path MODSDIR is C:\Users\chris\AppData\Roaming\.minecraft\mods
[22Apr2020 02:18:31.455] [main/DEBUG] [net.minecraftforge.fml.loading.FileUtils/CORE]: Found existing CONFIGDIR directory : C:\Users\chris\AppData\Roaming\.minecraft\config
[22Apr2020 02:18:31.455] [main/DEBUG] [net.minecraftforge.fml.loading.FMLPaths/CORE]: Path CONFIGDIR is C:\Users\chris\AppData\Roaming\.minecraft\config
[22Apr2020 02:18:31.455] [main/DEBUG] [net.minecraftforge.fml.loading.FMLPaths/CORE]: Path FMLCONFIG is C:\Users\chris\AppData\Roaming\.minecraft\config\fml.toml
[22Apr2020 02:18:31.455] [main/DEBUG] [net.minecraftforge.fml.loading.FMLServiceProvider/CORE]: Loading configuration
[22Apr2020 02:18:31.491] [main/DEBUG] [net.minecraftforge.fml.loading.FileUtils/CORE]: Found existing default config directory directory : C:\Users\chris\AppData\Roaming\.minecraft\defaultconfigs
[22Apr2020 02:18:31.491] [main/DEBUG] [net.minecraftforge.fml.loading.FMLServiceProvider/CORE]: Preparing launch handler
[22Apr2020 02:18:31.492] [main/DEBUG] [net.minecraftforge.fml.loading.FMLLoader/CORE]: Using fmlclient as launch service
[22Apr2020 02:18:31.495] [main/DEBUG] [net.minecraftforge.fml.loading.FMLLoader/CORE]: Received command line version data  : MC Version: '1.14.4' MCP Version: '20190829.143755' Forge Version: '28.1.0' Forge group: 'net.minecraftforge'
[22Apr2020 02:18:31.495] [main/DEBUG] [net.minecraftforge.fml.loading.LibraryFinder/CORE]: Found JAR asm at path C:\Users\chris\AppData\Roaming\.minecraft\libraries\org\ow2\asm\asm\6.2\asm-6.2.jar
[22Apr2020 02:18:31.495] [main/DEBUG] [net.minecraftforge.fml.loading.LibraryFinder/CORE]: Found probable library path C:\Users\chris\AppData\Roaming\.minecraft\libraries
[22Apr2020 02:18:31.496] [main/DEBUG] [net.minecraftforge.fml.loading.LibraryFinder/CORE]: Found forge path C:\Users\chris\AppData\Roaming\.minecraft\libraries\net\minecraftforge\forge\1.14.4-28.1.0\forge-1.14.4-28.1.0-universal.jar is present
[22Apr2020 02:18:31.496] [main/DEBUG] [net.minecraftforge.fml.loading.LibraryFinder/CORE]: SRG MC at C:\Users\chris\AppData\Roaming\.minecraft\libraries\net\minecraft\client\1.14.4-20190829.143755\client-1.14.4-20190829.143755-srg.jar is present
[22Apr2020 02:18:31.496] [main/DEBUG] [net.minecraftforge.fml.loading.LibraryFinder/CORE]: MC Extras at C:\Users\chris\AppData\Roaming\.minecraft\libraries\net\minecraft\client\1.14.4\client-1.14.4-extra.jar is present
[22Apr2020 02:18:31.496] [main/DEBUG] [net.minecraftforge.fml.loading.LibraryFinder/CORE]: Forge patches at C:\Users\chris\AppData\Roaming\.minecraft\libraries\net\minecraftforge\forge\1.14.4-28.1.0\forge-1.14.4-28.1.0-client.jar is present
[22Apr2020 02:18:31.498] [main/DEBUG] [net.minecraftforge.fml.loading.LanguageLoadingProvider/CORE]: Found 0 language providers
[22Apr2020 02:18:31.499] [main/DEBUG] [net.minecraftforge.fml.loading.LanguageLoadingProvider/CORE]: Adding forge as a language from C:\Users\chris\AppData\Roaming\.minecraft\libraries\net\minecraftforge\forge\1.14.4-28.1.0\forge-1.14.4-28.1.0-universal.jar
[22Apr2020 02:18:31.500] [main/DEBUG] [net.minecraftforge.fml.loading.LanguageLoadingProvider/CORE]: Adding file:/C:/Users/chris/AppData/Roaming/.minecraft/libraries/net/minecraftforge/forge/1.14.4-28.1.0/forge-1.14.4-28.1.0-universal.jar to languageloader classloader
[22Apr2020 02:18:31.521] [main/DEBUG] [net.minecraftforge.fml.loading.LanguageLoadingProvider/CORE]: Found 2 language providers
[22Apr2020 02:18:31.521] [main/DEBUG] [net.minecraftforge.fml.loading.LanguageLoadingProvider/CORE]: Found language provider javafml, version 28.1
[22Apr2020 02:18:31.523] [main/DEBUG] [net.minecraftforge.fml.loading.LanguageLoadingProvider/CORE]: Found language provider minecraft, version 1
[22Apr2020 02:18:31.524] [main/DEBUG] [cpw.mods.modlauncher.TransformationServiceDecorator/MODLAUNCHER]: Initialized transformation service fml
[22Apr2020 02:18:31.524] [main/DEBUG] [cpw.mods.modlauncher.TransformationServiceDecorator/MODLAUNCHER]: Initializing transformation service mixinbootstrap
[22Apr2020 02:18:31.526] [main/DEBUG] [mixin/]: Mixin bootstrap service org.spongepowered.asm.service.mojang.MixinServiceLaunchWrapperBootstrap is not available: LaunchWrapper is not available
[22Apr2020 02:18:31.530] [main/DEBUG] [mixin/]: MixinService [ModLauncher] was successfully booted in sun.misc.Launcher$AppClassLoader@4aa298b7
[22Apr2020 02:18:31.530] [main/DEBUG] [mixin/]: MixinService [ModLauncher] is not valid
[22Apr2020 02:18:31.533] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: org.spongepowered.asm.service.ServiceNotAvailableError: No mixin host service is available. Services: INVALID[ModLauncher] and 1 other invalid services.
[22Apr2020 02:18:31.533] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at org.spongepowered.asm.service.MixinService.initService(MixinService.java:159)
[22Apr2020 02:18:31.533] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at org.spongepowered.asm.service.MixinService.getServiceInstance(MixinService.java:125)
[22Apr2020 02:18:31.533] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at org.spongepowered.asm.service.MixinService.getService(MixinService.java:120)
[22Apr2020 02:18:31.534] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at org.spongepowered.asm.launch.MixinBootstrap.<clinit>(MixinBootstrap.java:78)
[22Apr2020 02:18:31.534] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at org.spongepowered.asm.launch.MixinTransformationService.initialize(MixinTransformationService.java:84)
[22Apr2020 02:18:31.534] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at io.github.lxgaming.mixin.launch.MixinTransformationService.lambda$initialize$2(MixinTransformationService.java:82)
[22Apr2020 02:18:31.534] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at io.github.lxgaming.mixin.launch.MixinTransformationService$$Lambda$144/1839337592.accept(Unknown Source)
[22Apr2020 02:18:31.534] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at java.lang.Iterable.forEach(Iterable.java:75)
[22Apr2020 02:18:31.535] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at io.github.lxgaming.mixin.launch.MixinTransformationService.initialize(MixinTransformationService.java:82)
[22Apr2020 02:18:31.535] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at cpw.mods.modlauncher.TransformationServiceDecorator.onInitialize(TransformationServiceDecorator.java:67)
[22Apr2020 02:18:31.535] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at cpw.mods.modlauncher.TransformationServicesHandler.lambda$initialiseTransformationServices$7(TransformationServicesHandler.java:106)
[22Apr2020 02:18:31.535] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at cpw.mods.modlauncher.TransformationServicesHandler$$Lambda$86/989447607.accept(Unknown Source)
[22Apr2020 02:18:31.535] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at java.util.HashMap$Values.forEach(HashMap.java:972)
[22Apr2020 02:18:31.535] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at cpw.mods.modlauncher.TransformationServicesHandler.initialiseTransformationServices(TransformationServicesHandler.java:106)
[22Apr2020 02:18:31.536] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at cpw.mods.modlauncher.TransformationServicesHandler.initializeTransformationServices(TransformationServicesHandler.java:59)
[22Apr2020 02:18:31.536] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at cpw.mods.modlauncher.Launcher.run(Launcher.java:75)
[22Apr2020 02:18:31.536] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at cpw.mods.modlauncher.Launcher.main(Launcher.java:65)
```
</details>

Here is my debug.log after the crash

**Comment by LXGaming** [comment]
For 1.14.4 you need Forge 28.1.45 or later

**Comment by Huntifer** [comment]
Nevermind! Issue was too old of Forge :) Just read previous and found that out, can leave this open so others can see or close this; is it listed on the bootstrap post on the forge website that you need forge 28.1.45 or later?
If so I just missed it, if not it may help people who run into it like me :) Ty for fast reply!

**Comment by LXGaming** [comment]
No problem.
I do have compatibility list here: https://github.com/LXGaming/MixinBootstrap#compatibility
