### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by Leiocera** [LXGaming/MixinBootstrap#20]
If I start Minecraft with this mod, Minecraft crashes. 

PLEASE HELP!!!

**Comment by LXGaming** [comment]
Please provide your debug.log file

**Comment by Leiocera** [comment]
There is no log file.

![image](https://user-images.githubusercontent.com/65770087/84592349-5af1e480-ae45-11ea-9506-fbe064111cc1.png)

**Comment by LXGaming** [comment]
You need to find the Minecraft folder, there will be a folder called `logs` which will contain the `debug.log` file

**Comment by Leiocera** [comment]
![image](https://user-images.githubusercontent.com/65770087/84592740-29c6e380-ae48-11ea-9ae0-cac8b5aef4f9.png)

**Comment by LXGaming** [comment]
Upload the `latest.log`, hopefully it will provide enough information to track down the source of the crashing.

**Comment by LeioceraYT** [comment]
[13:44:59] [main/INFO]: ModLauncher running: args [--username, LeioceraYT, --version, forge-31.2.9, --gameDir, C:\Users\LeioceraYT\Twitch\Minecraft\Instances\DOORSOFINFINITY, --assetsDir, C:\Users\LeioceraYT\Twitch\Minecraft\Install\assets, --assetIndex, 1.15, --uuid, f1aeb725a16943c4b8659a17ab5f4b55, --accessToken, ????????, --userType, mojang, --versionType, release, --width, 1024, --height, 768, --launchTarget, fmlclient, --fml.forgeVersion, 31.2.9, --fml.mcVersion, 1.15.2, --fml.forgeGroup, net.minecraftforge, --fml.mcpVersion, 20200515.085601]
[13:44:59] [main/INFO]: ModLauncher 5.1.0+69+master.79f13f7 starting: java version 1.8.0_51 by Oracle Corporation
[13:45:00] [main/INFO]: OptiFineTransformationService.onLoad
[13:45:00] [main/INFO]: OptiFine ZIP file: C:\Users\Manuel\Twitch\Minecraft\Instances\DOORSOFINFINITY\mods\OptiFine_1.15.2_HD_U_G1_pre18_MOD.jar
[13:45:00] [main/INFO]: Added Lets Encrypt root certificates as additional trust
[13:45:00] [main/INFO]: OptiFineTransformationService.initialize
[13:45:01] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8 Source=file:/C:/Users/Manuel/Twitch/Minecraft/Instances/DOORSOFINFINITY/mods/MixinBootstrap-1.0.3.jar Service=ModLauncher Env=CLIENT
[13:45:01] [main/WARN]: File C:\Users\Manuel\Twitch\Minecraft\Instances\DOORSOFINFINITY\mods\doorsofinfinity-1.0.1.jar has been ignored - it is invalid
[13:45:01] [main/WARN]: Mod file Mod File: C:\Users\Manuel\Twitch\Minecraft\Instances\DOORSOFINFINITY\mods\Skin Swapper 1.15.2.jar is missing mods.toml file
[13:45:01] [main/WARN]: File C:\Users\Manuel\Twitch\Minecraft\Instances\DOORSOFINFINITY\mods\Skin Swapper 1.15.2.jar has been ignored - it is invalid
[13:45:02] [main/INFO]: OptiFineTransformationService.transformers
[13:45:02] [main/INFO]: Targets: 278
[13:45:02] [main/INFO]: additionalClassesLocator: [optifine., net.optifine.]
[13:45:02] [main/INFO]: Successfully loaded Mixin Connector [com.qouteall.hiding_in_the_bushes.MyMixinConnector]
[13:45:02] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: java.lang.NoClassDefFoundError: net/minecraft/util/math/RayTraceResult
[13:45:02] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at com.qouteall.hiding_in_the_bushes.MyMixinConnector.connect(MyMixinConnector.java:13)
[13:45:02] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at org.spongepowered.asm.launch.platform.MixinConnectorManager.initConnectors(MixinConnectorManager.java:96)
[13:45:02] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at org.spongepowered.asm.launch.platform.MixinConnectorManager.inject(MixinConnectorManager.java:61)
[13:45:02] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at org.spongepowered.asm.launch.platform.MixinPlatformManager.inject(MixinPlatformManager.java:197)
[13:45:02] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at org.spongepowered.asm.launch.MixinBootstrap.inject(MixinBootstrap.java:190)
[13:45:02] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at org.spongepowered.asm.launch.MixinLaunchPlugin.initializeLaunch(MixinLaunchPlugin.java:194)
[13:45:02] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at cpw.mods.modlauncher.LaunchPluginHandler.lambda$announceLaunch$12(LaunchPluginHandler.java:95)
[13:45:02] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at cpw.mods.modlauncher.LaunchPluginHandler$$Lambda$427/2074492901.accept(Unknown Source)
[13:45:02] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at java.util.HashMap.forEach(HashMap.java:1280)
[13:45:02] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at cpw.mods.modlauncher.LaunchPluginHandler.announceLaunch(LaunchPluginHandler.java:95)
[13:45:02] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:52)
[13:45:02] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72)
[13:45:02] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at cpw.mods.modlauncher.Launcher.run(Launcher.java:81)
[13:45:02] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at cpw.mods.modlauncher.Launcher.main(Launcher.java:65)
[13:45:02] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1061]: Caused by: java.lang.ClassNotFoundException: net.minecraft.util.math.RayTraceResult
[13:45:02] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1061]: 	at java.lang.ClassLoader.findClass(ClassLoader.java:530)
[13:45:02] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1061]: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
[13:45:02] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1061]: 	at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:101)
[13:45:02] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1061]: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
[13:45:02] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1061]: 	... 14 more

**Comment by Leiocera** [comment]
[13:44:59] [main/INFO]: ModLauncher running: args [--username, LeioceraYT, --version, forge-31.2.9, --gameDir, C:\Users\LeioceraYT\Twitch\Minecraft\Instances\DOORSOFINFINITY, --assetsDir, C:\Users\LeioceraYT\Twitch\Minecraft\Install\assets, --assetIndex, 1.15, --uuid, f1aeb725a16943c4b8659a17ab5f4b55, --accessToken, ????????, --userType, mojang, --versionType, release, --width, 1024, --height, 768, --launchTarget, fmlclient, --fml.forgeVersion, 31.2.9, --fml.mcVersion, 1.15.2, --fml.forgeGroup, net.minecraftforge, --fml.mcpVersion, 20200515.085601]
[13:44:59] [main/INFO]: ModLauncher 5.1.0+69+master.79f13f7 starting: java version 1.8.0_51 by Oracle Corporation
[13:45:00] [main/INFO]: OptiFineTransformationService.onLoad
[13:45:00] [main/INFO]: OptiFine ZIP file: C:\Users\LeioceraYT\Twitch\Minecraft\Instances\DOORSOFINFINITY\mods\OptiFine_1.15.2_HD_U_G1_pre18_MOD.jar
[13:45:00] [main/INFO]: Added Lets Encrypt root certificates as additional trust
[13:45:00] [main/INFO]: OptiFineTransformationService.initialize
[13:45:01] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8 Source=file:/C:/Users/LeioceraYT/Twitch/Minecraft/Instances/DOORSOFINFINITY/mods/MixinBootstrap-1.0.3.jar Service=ModLauncher Env=CLIENT
[13:45:01] [main/WARN]: File C:\Users\LeioceraYT\Twitch\Minecraft\Instances\DOORSOFINFINITY\mods\doorsofinfinity-1.0.1.jar has been ignored - it is invalid
[13:45:01] [main/WARN]: Mod file Mod File: C:\Users\LeioceraYT\Twitch\Minecraft\Instances\DOORSOFINFINITY\mods\Skin Swapper 1.15.2.jar is missing mods.toml file
[13:45:01] [main/WARN]: File C:\Users\LeioceraYT\Twitch\Minecraft\Instances\DOORSOFINFINITY\mods\Skin Swapper 1.15.2.jar has been ignored - it is invalid
[13:45:02] [main/INFO]: OptiFineTransformationService.transformers
[13:45:02] [main/INFO]: Targets: 278
[13:45:02] [main/INFO]: additionalClassesLocator: [optifine., net.optifine.]
[13:45:02] [main/INFO]: Successfully loaded Mixin Connector [com.qouteall.hiding_in_the_bushes.MyMixinConnector]
[13:45:02] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: java.lang.NoClassDefFoundError: net/minecraft/util/math/RayTraceResult
[13:45:02] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at com.qouteall.hiding_in_the_bushes.MyMixinConnector.connect(MyMixinConnector.java:13)
[13:45:02] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at org.spongepowered.asm.launch.platform.MixinConnectorManager.initConnectors(MixinConnectorManager.java:96)
[13:45:02] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at org.spongepowered.asm.launch.platform.MixinConnectorManager.inject(MixinConnectorManager.java:61)
[13:45:02] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at org.spongepowered.asm.launch.platform.MixinPlatformManager.inject(MixinPlatformManager.java:197)
[13:45:02] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at org.spongepowered.asm.launch.MixinBootstrap.inject(MixinBootstrap.java:190)
[13:45:02] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at org.spongepowered.asm.launch.MixinLaunchPlugin.initializeLaunch(MixinLaunchPlugin.java:194)
[13:45:02] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at cpw.mods.modlauncher.LaunchPluginHandler.lambda$announceLaunch$12(LaunchPluginHandler.java:95)
[13:45:02] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at cpw.mods.modlauncher.LaunchPluginHandler$$Lambda$427/2074492901.accept(Unknown Source)
[13:45:02] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at java.util.HashMap.forEach(HashMap.java:1280)
[13:45:02] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at cpw.mods.modlauncher.LaunchPluginHandler.announceLaunch(LaunchPluginHandler.java:95)
[13:45:02] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:52)
[13:45:02] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72)
[13:45:02] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at cpw.mods.modlauncher.Launcher.run(Launcher.java:81)
[13:45:02] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at cpw.mods.modlauncher.Launcher.main(Launcher.java:65)
[13:45:02] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1061]: Caused by: java.lang.ClassNotFoundException: net.minecraft.util.math.RayTraceResult
[13:45:02] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1061]: 	at java.lang.ClassLoader.findClass(ClassLoader.java:530)
[13:45:02] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1061]: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
[13:45:02] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1061]: 	at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:101)
[13:45:02] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1061]: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
[13:45:02] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1061]: 	... 14 more

**Comment by Leiocera** [comment]
I've just copy-pasted it.

Can you do something with that?

**Comment by LXGaming** [comment]
Looks like an issue with [ImmersivePortals](https://github.com/qouteall/ImmersivePortalsModForForge) what seems to be happening is they are loading a Helper class in [MyMixinConnector.java#L13](https://github.com/qouteall/ImmersivePortalsModForForge/blob/3d67ed88a316a89823a49ed9aea81fa3b28f4a88/src/main/java/com/qouteall/hiding_in_the_bushes/MyMixinConnector.java#L13) which is then loading in Minecraft classes which are not yet present which is resulting in a ClassNotFoundException

**Comment by Leiocera** [comment]
I don't know what you mean xD

How can I solve this problem?

**Comment by LXGaming** [comment]
Open an issue on https://github.com/qouteall/ImmersivePortalsModForForge/issues and add a link so they can find this issue.

This is a bug that ImmersivePortals needs to fix

**Comment by Leiocera** [comment]
https://www.youtube.com/watch?v=qHPh1Xg5ba8

**Comment by Leiocera** [comment]
There's the bug

**Comment by Leiocera** [comment]
Can you help me?

**Comment by LXGaming** [comment]
Create an issue on ImmersivePortals GitHub.

**Comment by ghost** [comment]
this should be closed
