### ISSUE TITLE
Crashed when loading forge client

### ISSUE THREAD

**Issue by Zikandr** [LXGaming/MixinBootstrap#31]
- MixinBootstrap version: 1.0.3
- Forge version: 32.0.61
- Minecraft version: 1.16.1
- Java version: 1.8.0_221
- Mods: 
OptiForge 1.16.1-0.1.2,
OptiFine 1.16.1_HD_U_G2_pre3
Worldedit 1.16.1-7.2.0 beta 02

The client tries to load and after about four seconds, it crashes.

EDIT: I accidentially attached the file, here are the logs:
`[10Jul2020 11:47:34.568] [main/INFO] [cpw.mods.modlauncher.Launcher/MODLAUNCHER]: ModLauncher running: args [--username, Zikandr, --version, 1.16.1-forge-32.0.61, --gameDir, C:\Users\Sikandr\AppData\Roaming\.optiforge1.16.1, --assetsDir, C:\Users\Sikandr\AppData\Roaming\.minecraft\assets, --assetIndex, 1.16, --uuid, 438437ca1c794ad8883e47a463ea0dbd, --accessToken, ????????, --userType, mojang, --versionType, release, --launchTarget, fmlclient, --fml.forgeVersion, 32.0.61, --fml.mcVersion, 1.16.1, --fml.forgeGroup, net.minecraftforge, --fml.mcpVersion, 20200625.160719]
[10Jul2020 11:47:34.572] [main/INFO] [cpw.mods.modlauncher.Launcher/MODLAUNCHER]: ModLauncher 5.1.0+69+master.79f13f7 starting: java version 1.8.0_51 by Oracle Corporation
[10Jul2020 11:47:34.690] [main/INFO] [optifine.OptiFineTransformationService/]: OptiFineTransformationService.onLoad
[10Jul2020 11:47:34.692] [main/INFO] [optifine.OptiFineTransformationService/]: OptiFine ZIP file: C:\Users\Sikandr\AppData\Roaming\.optiforge1.16.1\mods\preview_OptiFine_1.16.1_HD_U_G2_pre3.jar
[10Jul2020 11:47:34.781] [main/INFO] [net.minecraftforge.fml.loading.FixSSL/CORE]: Added Lets Encrypt root certificates as additional trust
[10Jul2020 11:47:34.812] [main/INFO] [optifine.OptiFineTransformationService/]: OptiFineTransformationService.initialize
[10Jul2020 11:47:35.596] [main/INFO] [mixin/]: SpongePowered MIXIN Subsystem Version=0.8 Source=file:/C:/Users/Sikandr/AppData/Roaming/.optiforge1.16.1/mods/MixinBootstrap-1.0.3.jar Service=ModLauncher Env=CLIENT
[10Jul2020 11:47:36.304] [main/INFO] [optifine.OptiFineTransformationService/]: OptiFineTransformationService.transformers
[10Jul2020 11:47:36.345] [main/INFO] [optifine.OptiFineTransformer/]: Targets: 289
[10Jul2020 11:47:36.629] [main/INFO] [optifine.OptiFineTransformationService/]: additionalClassesLocator: [optifine., net.optifine.]
[10Jul2020 11:47:36.678] [main/INFO] [cpw.mods.modlauncher.LaunchServiceHandler/MODLAUNCHER]: Launching target 'fmlclient' with arguments [--version, 1.16.1-forge-32.0.61, --gameDir, C:\Users\Sikandr\AppData\Roaming\.optiforge1.16.1, --assetsDir, C:\Users\Sikandr\AppData\Roaming\.minecraft\assets, --uuid, 438437ca1c794ad8883e47a463ea0dbd, --username, Zikandr, --assetIndex, 1.16, --accessToken, ????????, --userType, mojang, --versionType, release]
[10Jul2020 11:47:36.784] [main/INFO] [OptiForge/]:  - Add a transformer: io.github.zekerzhayard.optiforge.asm.transformers.net.minecraft.client.gui.IngameGuiTransformer
[10Jul2020 11:47:36.786] [main/INFO] [OptiForge/]:  - Add a transformer: io.github.zekerzhayard.optiforge.asm.transformers.net.minecraft.client.renderer.ItemRendererTransformer
[10Jul2020 11:47:36.788] [main/INFO] [OptiForge/]:  - Add a transformer: io.github.zekerzhayard.optiforge.asm.transformers.net.minecraft.client.renderer.OverlayRendererTransformer
[10Jul2020 11:47:36.789] [main/INFO] [OptiForge/]:  - Add a transformer: io.github.zekerzhayard.optiforge.asm.transformers.net.minecraft.client.renderer.entity.ItemFrameRendererTransformer
[10Jul2020 11:47:36.792] [main/INFO] [OptiForge/]: Add 4 transformer(s) totally.
[10Jul2020 11:47:36.797] [main/INFO] [OptiForge/]:  - Add an annotation action: io.github.zekerzhayard.optiforge.asm.utils.annotations.DynamicShadow$AnnotationAction
[10Jul2020 11:47:36.800] [main/INFO] [OptiForge/]:  - Add an annotation action: io.github.zekerzhayard.optiforge.asm.utils.annotations.LazyOverwrite$AnnotationAction
[10Jul2020 11:47:36.803] [main/INFO] [OptiForge/]:  - Add an annotation action: io.github.zekerzhayard.optiforge.asm.utils.annotations.MarkStatic$AnnotationAction
[10Jul2020 11:47:36.805] [main/INFO] [OptiForge/]:  - Add an annotation action: io.github.zekerzhayard.optiforge.asm.utils.annotations.RedirectSurrogate$AnnotationAction
[10Jul2020 11:47:36.805] [main/INFO] [OptiForge/]: Add 4 annotation action(s) totally.
[10Jul2020 11:47:38.221] [main/INFO] [OptiForge/]: [PRE] Found a transformer "io.github.zekerzhayard.optiforge.asm.transformers.net.minecraft.client.renderer.entity.ItemFrameRendererTransformer" for class "net.minecraft.client.renderer.entity.ItemFrameRenderer"
[10Jul2020 11:47:38.241] [main/INFO] [OptiForge/]: [POST] Found a transformer "io.github.zekerzhayard.optiforge.asm.transformers.net.minecraft.client.renderer.entity.ItemFrameRendererTransformer" for class "net.minecraft.client.renderer.entity.ItemFrameRenderer"
[10Jul2020 11:47:38.325] [main/INFO] [OptiForge/]: [PRE] Found a transformer "io.github.zekerzhayard.optiforge.asm.transformers.net.minecraft.client.gui.IngameGuiTransformer" for class "net.minecraft.client.gui.IngameGui"
[10Jul2020 11:47:38.330] [main/INFO] [OptiForge/]: [POST] Found a transformer "io.github.zekerzhayard.optiforge.asm.transformers.net.minecraft.client.gui.IngameGuiTransformer" for class "net.minecraft.client.gui.IngameGui"
[10Jul2020 11:47:38.531] [main/INFO] [OptiForge/]: [PRE] Found a transformer "io.github.zekerzhayard.optiforge.asm.transformers.net.minecraft.client.renderer.ItemRendererTransformer" for class "net.minecraft.client.renderer.ItemRenderer"
[10Jul2020 11:47:38.537] [main/INFO] [OptiForge/]: [POST] Found a transformer "io.github.zekerzhayard.optiforge.asm.transformers.net.minecraft.client.renderer.ItemRendererTransformer" for class "net.minecraft.client.renderer.ItemRenderer"
[10Jul2020 11:47:38.603] [main/INFO] [STDERR/]: [org.spongepowered.asm.mixin.transformer.MixinProcessor:applyMixins:362]: org.spongepowered.asm.mixin.injection.throwables.InjectionError: Critical injection failure: Redirector redirect$setForgeKeybindProperties$0(Ljava/lang/Object;Ljava/lang/Object;[Ljava/lang/Object;)Ljava/lang/Object; in mixins.optiforge.json:net.minecraft.client.MixinGameSettings failed injection check, (0/1) succeeded. Scanned 1 target(s). Using refmap mixins.optiforge.refmap.json
[10Jul2020 11:47:38.603] [main/INFO] [STDERR/]: [org.spongepowered.asm.mixin.transformer.MixinProcessor:applyMixins:362]: 	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.postInject(InjectionInfo.java:400)
[10Jul2020 11:47:38.603] [main/INFO] [STDERR/]: [org.spongepowered.asm.mixin.transformer.MixinProcessor:applyMixins:362]: 	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.applyInjections(MixinTargetContext.java:1280)
[10Jul2020 11:47:38.603] [main/INFO] [STDERR/]: [org.spongepowered.asm.mixin.transformer.MixinProcessor:applyMixins:362]: 	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyInjections(MixinApplicatorStandard.java:1042)
[10Jul2020 11:47:38.604] [main/INFO] [STDERR/]: [org.spongepowered.asm.mixin.transformer.MixinProcessor:applyMixins:362]: 	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:395)
[10Jul2020 11:47:38.604] [main/INFO] [STDERR/]: [org.spongepowered.asm.mixin.transformer.MixinProcessor:applyMixins:362]: 	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:320)
[10Jul2020 11:47:38.604] [main/INFO] [STDERR/]: [org.spongepowered.asm.mixin.transformer.MixinProcessor:applyMixins:362]: 	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:345)
[10Jul2020 11:47:38.604] [main/INFO] [STDERR/]: [org.spongepowered.asm.mixin.transformer.MixinProcessor:applyMixins:362]: 	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:570)
[10Jul2020 11:47:38.604] [main/INFO] [STDERR/]: [org.spongepowered.asm.mixin.transformer.MixinProcessor:applyMixins:362]: 	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:351)
[10Jul2020 11:47:38.604] [main/INFO] [STDERR/]: [org.spongepowered.asm.mixin.transformer.MixinProcessor:applyMixins:362]: 	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:206)
[10Jul2020 11:47:38.605] [main/INFO] [STDERR/]: [org.spongepowered.asm.mixin.transformer.MixinProcessor:applyMixins:362]: 	at org.spongepowered.asm.mixin.transformer.MixinTransformationHandler.processClass(MixinTransformationHandler.java:109)
[10Jul2020 11:47:38.605] [main/INFO] [STDERR/]: [org.spongepowered.asm.mixin.transformer.MixinProcessor:applyMixins:362]: 	at org.spongepowered.asm.launch.MixinLaunchPlugin.processClass(MixinLaunchPlugin.java:135)
[10Jul2020 11:47:38.605] [main/INFO] [STDERR/]: [org.spongepowered.asm.mixin.transformer.MixinProcessor:applyMixins:362]: 	at cpw.mods.modlauncher.LaunchPluginHandler.offerClassNodeToPlugins(LaunchPluginHandler.java:85)
[10Jul2020 11:47:38.605] [main/INFO] [STDERR/]: [org.spongepowered.asm.mixin.transformer.MixinProcessor:applyMixins:362]: 	at cpw.mods.modlauncher.ClassTransformer.transform(ClassTransformer.java:115)
[10Jul2020 11:47:38.605] [main/INFO] [STDERR/]: [org.spongepowered.asm.mixin.transformer.MixinProcessor:applyMixins:362]: 	at cpw.mods.modlauncher.TransformingClassLoader$DelegatedClassLoader.findClass(TransformingClassLoader.java:239)
[10Jul2020 11:47:38.605] [main/INFO] [STDERR/]: [org.spongepowered.asm.mixin.transformer.MixinProcessor:applyMixins:362]: 	at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:126)
[10Jul2020 11:47:38.606] [main/INFO] [STDERR/]: [org.spongepowered.asm.mixin.transformer.MixinProcessor:applyMixins:362]: 	at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:96)
[10Jul2020 11:47:38.606] [main/INFO] [STDERR/]: [org.spongepowered.asm.mixin.transformer.MixinProcessor:applyMixins:362]: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
[10Jul2020 11:47:38.606] [main/INFO] [STDERR/]: [org.spongepowered.asm.mixin.transformer.MixinProcessor:applyMixins:362]: 	at java.lang.Class.getDeclaredFields0(Native Method)
[10Jul2020 11:47:38.606] [main/INFO] [STDERR/]: [org.spongepowered.asm.mixin.transformer.MixinProcessor:applyMixins:362]: 	at java.lang.Class.privateGetDeclaredFields(Class.java:2583)
[10Jul2020 11:47:38.606] [main/INFO] [STDERR/]: [org.spongepowered.asm.mixin.transformer.MixinProcessor:applyMixins:362]: 	at java.lang.Class.getDeclaredFields(Class.java:1916)
[10Jul2020 11:47:38.607] [main/INFO] [STDERR/]: [org.spongepowered.asm.mixin.transformer.MixinProcessor:applyMixins:362]: 	at net.optifine.reflect.FieldLocatorTypes.<init>(FieldLocatorTypes.java:25)
[10Jul2020 11:47:38.607] [main/INFO] [STDERR/]: [org.spongepowered.asm.mixin.transformer.MixinProcessor:applyMixins:362]: 	at net.optifine.reflect.Reflector.<clinit>(Reflector.java:516)
[10Jul2020 11:47:38.607] [main/INFO] [STDERR/]: [org.spongepowered.asm.mixin.transformer.MixinProcessor:applyMixins:362]: 	at net.minecraft.crash.CrashReport.func_71504_g(CrashReport.java:101)
[10Jul2020 11:47:38.607] [main/INFO] [STDERR/]: [org.spongepowered.asm.mixin.transformer.MixinProcessor:applyMixins:362]: 	at net.minecraft.crash.CrashReport.<init>(CrashReport.java:54)
[10Jul2020 11:47:38.607] [main/INFO] [STDERR/]: [org.spongepowered.asm.mixin.transformer.MixinProcessor:applyMixins:362]: 	at net.minecraft.crash.CrashReport.func_230188_h_(CrashReport.java:413)
[10Jul2020 11:47:38.607] [main/INFO] [STDERR/]: [org.spongepowered.asm.mixin.transformer.MixinProcessor:applyMixins:362]: 	at net.minecraft.client.main.Main.main(Main.java:122)
[10Jul2020 11:47:38.608] [main/INFO] [STDERR/]: [org.spongepowered.asm.mixin.transformer.MixinProcessor:applyMixins:362]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[10Jul2020 11:47:38.608] [main/INFO] [STDERR/]: [org.spongepowered.asm.mixin.transformer.MixinProcessor:applyMixins:362]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[10Jul2020 11:47:38.608] [main/INFO] [STDERR/]: [org.spongepowered.asm.mixin.transformer.MixinProcessor:applyMixins:362]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[10Jul2020 11:47:38.608] [main/INFO] [STDERR/]: [org.spongepowered.asm.mixin.transformer.MixinProcessor:applyMixins:362]: 	at java.lang.reflect.Method.invoke(Method.java:497)
[10Jul2020 11:47:38.608] [main/INFO] [STDERR/]: [org.spongepowered.asm.mixin.transformer.MixinProcessor:applyMixins:362]: 	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51)
[10Jul2020 11:47:38.608] [main/INFO] [STDERR/]: [org.spongepowered.asm.mixin.transformer.MixinProcessor:applyMixins:362]: 	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$440/1186657657.call(Unknown Source)
[10Jul2020 11:47:38.608] [main/INFO] [STDERR/]: [org.spongepowered.asm.mixin.transformer.MixinProcessor:applyMixins:362]: 	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37)
[10Jul2020 11:47:38.608] [main/INFO] [STDERR/]: [org.spongepowered.asm.mixin.transformer.MixinProcessor:applyMixins:362]: 	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54)
[10Jul2020 11:47:38.609] [main/INFO] [STDERR/]: [org.spongepowered.asm.mixin.transformer.MixinProcessor:applyMixins:362]: 	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72)
[10Jul2020 11:47:38.609] [main/INFO] [STDERR/]: [org.spongepowered.asm.mixin.transformer.MixinProcessor:applyMixins:362]: 	at cpw.mods.modlauncher.Launcher.run(Launcher.java:81)
[10Jul2020 11:47:38.609] [main/INFO] [STDERR/]: [org.spongepowered.asm.mixin.transformer.MixinProcessor:applyMixins:362]: 	at cpw.mods.modlauncher.Launcher.main(Launcher.java:65)
[10Jul2020 11:47:38.609] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
[10Jul2020 11:47:38.609] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:39)
[10Jul2020 11:47:38.609] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54)
[10Jul2020 11:47:38.609] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72)
[10Jul2020 11:47:38.609] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at cpw.mods.modlauncher.Launcher.run(Launcher.java:81)
[10Jul2020 11:47:38.610] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at cpw.mods.modlauncher.Launcher.main(Launcher.java:65)
[10Jul2020 11:47:38.610] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1061]: Caused by: java.lang.reflect.InvocationTargetException
[10Jul2020 11:47:38.610] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1061]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[10Jul2020 11:47:38.610] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1061]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[10Jul2020 11:47:38.610] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1061]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[10Jul2020 11:47:38.610] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1061]: 	at java.lang.reflect.Method.invoke(Method.java:497)
[10Jul2020 11:47:38.610] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1061]: 	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51)
[10Jul2020 11:47:38.610] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1061]: 	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$440/1186657657.call(Unknown Source)
[10Jul2020 11:47:38.610] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1061]: 	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37)
[10Jul2020 11:47:38.610] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1061]: 	... 4 more
[10Jul2020 11:47:38.611] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:643]: Caused by: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
[10Jul2020 11:47:38.611] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:643]: 	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:364)
[10Jul2020 11:47:38.611] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:643]: 	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:206)
[10Jul2020 11:47:38.611] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:643]: 	at org.spongepowered.asm.mixin.transformer.MixinTransformationHandler.processClass(MixinTransformationHandler.java:109)
[10Jul2020 11:47:38.611] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:643]: 	at org.spongepowered.asm.launch.MixinLaunchPlugin.processClass(MixinLaunchPlugin.java:135)
[10Jul2020 11:47:38.611] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:643]: 	at cpw.mods.modlauncher.LaunchPluginHandler.offerClassNodeToPlugins(LaunchPluginHandler.java:85)
[10Jul2020 11:47:38.611] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:643]: 	at cpw.mods.modlauncher.ClassTransformer.transform(ClassTransformer.java:115)
[10Jul2020 11:47:38.611] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:643]: 	at cpw.mods.modlauncher.TransformingClassLoader$DelegatedClassLoader.findClass(TransformingClassLoader.java:239)
[10Jul2020 11:47:38.611] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:643]: 	at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:126)
[10Jul2020 11:47:38.612] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:643]: 	at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:96)
[10Jul2020 11:47:38.612] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:643]: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
[10Jul2020 11:47:38.612] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:643]: 	at java.lang.Class.getDeclaredFields0(Native Method)
[10Jul2020 11:47:38.612] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:643]: 	at java.lang.Class.privateGetDeclaredFields(Class.java:2583)
[10Jul2020 11:47:38.612] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:643]: 	at java.lang.Class.getDeclaredFields(Class.java:1916)
[10Jul2020 11:47:38.612] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:643]: 	at net.optifine.reflect.FieldLocatorTypes.<init>(FieldLocatorTypes.java:25)
[10Jul2020 11:47:38.612] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:643]: 	at net.optifine.reflect.Reflector.<clinit>(Reflector.java:516)
[10Jul2020 11:47:38.612] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:643]: 	at net.minecraft.crash.CrashReport.func_71504_g(CrashReport.java:101)
[10Jul2020 11:47:38.612] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:643]: 	at net.minecraft.crash.CrashReport.<init>(CrashReport.java:54)
[10Jul2020 11:47:38.613] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:643]: 	at net.minecraft.crash.CrashReport.func_230188_h_(CrashReport.java:413)
[10Jul2020 11:47:38.613] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:643]: 	at net.minecraft.client.main.Main.main(Main.java:122)
[10Jul2020 11:47:38.613] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:643]: 	... 11 more
[10Jul2020 11:47:38.613] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:667]: Caused by: org.spongepowered.asm.mixin.injection.throwables.InjectionError: Critical injection failure: Redirector redirect$setForgeKeybindProperties$0(Ljava/lang/Object;Ljava/lang/Object;[Ljava/lang/Object;)Ljava/lang/Object; in mixins.optiforge.json:net.minecraft.client.MixinGameSettings failed injection check, (0/1) succeeded. Scanned 1 target(s). Using refmap mixins.optiforge.refmap.json
[10Jul2020 11:47:38.613] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:667]: 	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.postInject(InjectionInfo.java:400)
[10Jul2020 11:47:38.613] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:667]: 	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.applyInjections(MixinTargetContext.java:1280)
[10Jul2020 11:47:38.613] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:667]: 	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyInjections(MixinApplicatorStandard.java:1042)
[10Jul2020 11:47:38.613] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:667]: 	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:395)
[10Jul2020 11:47:38.613] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:667]: 	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:320)
[10Jul2020 11:47:38.614] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:667]: 	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:345)
[10Jul2020 11:47:38.614] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:667]: 	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:570)
[10Jul2020 11:47:38.614] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:667]: 	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:351)
[10Jul2020 11:47:38.614] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:667]: 	... 29 more
`

**Comment by LXGaming** [comment]
Update OptiForge to vMC1.16.1-0.1.3 as that version supports OptiFine pre3.
