### ISSUE TITLE
NullPointerException

### ISSUE THREAD

**Issue by Craft1s** [LXGaming/MixinBootstrap#35]
**Environment**
- MixinBootstrap version: MixinBootstrap-1.0.3.jar
- Forge version: 1.12.2 (14.23.5.2847)
- Minecraft version: 1.12.2
- Java version: Latest(261)
- Mods: unloader@1.2.0,jei@4.16.1.302,cropdusting@0.7,wawla@2.6.275,neat@1.4-17,armoryexpansion-matteroverdrive@2.0.0-alpha,waystones@4.1.0,mcp@9.42,journeymap@1.12.2-5.7.1,placebo@1.6.0,conarm@1.2.5.9,surge@2.0.77,microblockcbe@2.6.2.83,inventorytweaks@1.64+dev.151.822d839,foamfixcore@7.7.4,randompatches@1.12.2-1.22.1.3,morpheus@1.12.2-3.5.106,moartinkers@0.6.0,ftblib@5.4.7.2,waila@1.8.26,enderstorage@2.4.6.137,jeresources@0.9.2.60,armoryexpansion@2.0.0-alpha,mcjtylib_ng@3.5.4,forge@14.23.5.2847,mob_grinding_utils@0.3.13,phosphor-lighting@1.12.2-0.2.7,ironchest@1.12.2-7.0.67.844,flyringbaublemod@0.3.1_1.12-d4e654e,armoryexpansion-conarm@2.0.0-alpha, minecraft@1.12.2,tconstruct@1.12.2-2.13.0.183,stackie@1.6.0.48,tinkertoolleveling@1.12.2-1.1.0.DEV.b23e769,torchmaster@1.8.1.82,baubles@1.5.2,yabba@1.1.2.54,chickenchunks@2.4.2.74,extrautils2@1.0,vanillafix@1.0.10-150,mantle@1.12-1.3.3.55,gravestone@1.10.3,bhc@2.0.3,lunatriuscore@1.2.0.42,fastbench@1.7.3,oreexcavation@1.4.150,FML@8.0.99.99,furnaceoverhaul@2.2.2,betterbedrock@5.1,fastfurnace@1.3.1,appleskin@1.0.14,minecraftmultipartcbe@2.6.2.83,moreoverlays@1.15.1,armoryexpansion-iceandfire@2.0.0-alpha,forgemultipartcbe@2.6.2.83,foamfix@0.10.10-1.12.2,armoryexpansion-custommaterials@2.0.0-alpha,codechickenlib@3.2.3.358,translocators@2.5.2.81,tinkersaddons@1.0.7,wailaharvestability@1.1.12

**Issue Description**
The log attached here is from my server because I suspected that the problem is in the server side. I'm fine playing my pack in single player mode but in my server I can login, interact things for a little while but after some seconds my game freezes then disconnects. And when I checked my mc's directory, the crash log is flooded by at least 100+ NullPointerException crash.txt(s) captured by VanillaFix and cause by unknown mod. I posted this issue here because I read some articles that this is caused by multiple mods(VanillaFix, Texfix, Phosphor, Performant, etc.) loading mixin, which creates a mod clash. 

https://mclo.gs/RSNzuvg

**Comment by LXGaming** [comment]
Can you please upload your clients `debug.log`.

**Comment by MagmaSlime123** [comment]
Mixin cause so many issues and compat. issues...

**Comment by Craft1s** [comment]
I'll add the latest.log too.
[debug.log](https://github.com/LXGaming/MixinBootstrap/files/5185820/debug.log)
[latest.log](https://github.com/LXGaming/MixinBootstrap/files/5185821/latest.log)

**Comment by LXGaming** [comment]
There are "Out of Memory" errors all over the place, You need to allocate more ram to your Minecraft Client, I can see you've only allocation 1 GB which is definitely not enough for Modded Minecraft.

**Comment by Craft1s** [comment]
Well, I'm not getting "Out of Memory" errors when I'm in single player unless I crank up the render distance to high and fly around very fast. And when I read the log, the error only appeared during the journey maps's minimap loading which I also noticed that the minimap disappears after some seconds of playing in the server.
[10:53:22] [Client thread/WARN] [journeymap]: TileDrawStep.updateRegionTexture is already running, cancelling first
[10:53:22] [Client thread/ERROR] [net.minecraft.client.Minecraft]: ########## GL ERROR ##########
[10:53:22] [Client thread/ERROR] [net.minecraft.client.Minecraft]: @ Post render
[10:53:22] [Client thread/ERROR] [net.minecraft.client.Minecraft]: 1285: Out of memory
[10:53:22] [Client thread/WARN] [journeymap]: TileDrawStep.updateRegionTexture is already running, cancelling first
[10:53:22] [Client thread/ERROR] [net.minecraft.client.Minecraft]: ########## GL ERROR ##########
[10:53:22] [Client thread/ERROR] [net.minecraft.client.Minecraft]: @ Post render
[10:53:22] [Client thread/ERROR] [net.minecraft.client.Minecraft]: 1285: Out of memory
[10:53:22] [Client thread/WARN] [journeymap]: TileDrawStep.updateRegionTexture is already running, cancelling first
[10:53:22] [Client thread/ERROR] [net.minecraft.client.Minecraft]: ########## GL ERROR ##########
[10:53:22] [Client thread/ERROR] [net.minecraft.client.Minecraft]: @ Post render
[10:53:22] [Client thread/ERROR] [net.minecraft.client.Minecraft]: 1285: Out of memory
[10:53:22] [Client thread/WARN] [journeymap]: TileDrawStep.updateRegionTexture is already running, cancelling first
[10:53:22] [Client thread/ERROR] [net.minecraft.client.Minecraft]: ########## GL ERROR ##########
[10:53:22] [Client thread/ERROR] [net.minecraft.client.Minecraft]: @ Post render
[10:53:22] [Client thread/ERROR] [net.minecraft.client.Minecraft]: 1285: Out of memory
[10:53:22] [Client thread/WARN] [journeymap]: TileDrawStep.updateRegionTexture is already running, cancelling first
[10:53:22] [Client thread/ERROR] [net.minecraft.client.Minecraft]: ########## GL ERROR ##########
[10:53:22] [Client thread/ERROR] [net.minecraft.client.Minecraft]: @ Post render
[10:53:22] [Client thread/ERROR] [net.minecraft.client.Minecraft]: 1285: Out of memory
[10:53:22] [Client thread/WARN] [journeymap]: TileDrawStep.updateRegionTexture is already running, cancelling first
[10:53:22] [Client thread/ERROR] [net.minecraft.client.Minecraft]: ########## GL ERROR ##########
[10:53:22] [Client thread/ERROR] [net.minecraft.client.Minecraft]: @ Post render
[10:53:22] [Client thread/ERROR] [net.minecraft.client.Minecraft]: 1285: Out of memory
[10:53:22] [Client thread/WARN] [journeymap]: TileDrawStep.updateRegionTexture is already running, cancelling first
[10:53:22] [Client thread/ERROR] [net.minecraft.client.Minecraft]: ########## GL ERROR ##########
[10:53:22] [Client thread/ERROR] [net.minecraft.client.Minecraft]: @ Post render
[10:53:22] [Client thread/ERROR] [net.minecraft.client.Minecraft]: 1285: Out of memory
[10:53:22] [Client thread/WARN] [journeymap]: TileDrawStep.updateRegionTexture is already running, cancelling first
[10:53:22] [Client thread/ERROR] [net.minecraft.client.Minecraft]: ########## GL ERROR ##########
[10:53:22] [Client thread/ERROR] [net.minecraft.client.Minecraft]: @ Post render
[10:53:22] [Client thread/ERROR] [net.minecraft.client.Minecraft]: 1285: Out of memory
[10:53:22] [Client thread/WARN] [journeymap]: TileDrawStep.updateRegionTexture is already running, cancelling first
[10:53:22] [Client thread/ERROR] [net.minecraft.client.Minecraft]: ########## GL ERROR ##########
[10:53:22] [Client thread/ERROR] [net.minecraft.client.Minecraft]: @ Post render
[10:53:22] [Client thread/ERROR] [net.minecraft.client.Minecraft]: 1285: Out of memory
[10:53:23] [Client thread/WARN] [journeymap]: TileDrawStep.updateRegionTexture is already running, cancelling first
[10:53:23] [Client thread/ERROR] [net.minecraft.client.Minecraft]: ########## GL ERROR ##########
[10:53:23] [Client thread/ERROR] [net.minecraft.client.Minecraft]: @ Post render
[10:53:23] [Client thread/ERROR] [net.minecraft.client.Minecraft]: 1285: Out of memory
[10:53:23] [Client thread/WARN] [journeymap]: TileDrawStep.updateRegionTexture is already running, cancelling first
[10:53:23] [Client thread/ERROR] [net.minecraft.client.Minecraft]: ########## GL ERROR ##########
[10:53:23] [Client thread/ERROR] [net.minecraft.client.Minecraft]: @ Post render
[10:53:23] [Client thread/ERROR] [net.minecraft.client.Minecraft]: 1285: Out of memory
[10:53:23] [Client thread/WARN] [journeymap]: TileDrawStep.updateRegionTexture is already running, cancelling first
[10:53:23] [Client thread/ERROR] [net.minecraft.client.Minecraft]: ########## GL ERROR ##########
[10:53:23] [Client thread/ERROR] [net.minecraft.client.Minecraft]: @ Post render
[10:53:23] [Client thread/ERROR] [net.minecraft.client.Minecraft]: 1285: Out of memory
[10:53:23] [Client thread/WARN] [journeymap]: TileDrawStep.updateRegionTexture is already running, cancelling first
[10:53:23] [Client thread/ERROR] [net.minecraft.client.Minecraft]: ########## GL ERROR ##########
[10:53:23] [Client thread/ERROR] [net.minecraft.client.Minecraft]: @ Post render
[10:53:23] [Client thread/ERROR] [net.minecraft.client.Minecraft]: 1285: Out of memory
[10:53:23] [Client thread/WARN] [journeymap]: TileDrawStep.updateRegionTexture is already running, cancelling first
[10:53:23] [Client thread/ERROR] [net.minecraft.client.Minecraft]: ########## GL ERROR ##########
[10:53:23] [Client thread/ERROR] [net.minecraft.client.Minecraft]: @ Post render
[10:53:23] [Client thread/ERROR] [net.minecraft.client.Minecraft]: 1285: Out of memory
And after a minute of playing, the client freezes because VanillaFix captures a ton of NullPointerException errors with no known cause. I cannot attach a crash file here because I already cleared the crash logs but I will try to replicate the error and attach the crash log here. And as far I've read the crash logs, I can't really tell that the problem is memory 'cause the client only uses 400-470MB of memory out of 888MB max 1011MB.

**Comment by covers1624** [comment]
```
[10:53:31] [Client thread/ERROR] [journeymap]: Error in JourneyMap.performMainThreadTasks(): java.lang.OutOfMemoryError
	at sun.misc.Unsafe.allocateMemory(Native Method)
	at java.nio.DirectByteBuffer.<init>(Unknown Source)
	at java.nio.ByteBuffer.allocateDirect(Unknown Source)
	at journeymap.client.render.texture.TextureImpl.setImage(TextureImpl.java:126)
	at journeymap.client.render.texture.TextureImpl.<init>(TextureImpl.java:90)
	at journeymap.client.render.texture.RegionTextureImpl.<init>(RegionTextureImpl.java:26)
	at journeymap.client.model.ImageHolder.getTexture(ImageHolder.java:161)
	at journeymap.client.model.ImageHolder.<init>(ImageHolder.java:53)
	at journeymap.client.model.ImageSet.addHolder(ImageSet.java:155)
	at journeymap.client.model.RegionImageSet.getHolder(RegionImageSet.java:42)
	at journeymap.client.render.map.TileDrawStep.getRegionTextureHolder(TileDrawStep.java:94)
	at journeymap.client.render.map.TileDrawStep.updateRegionTexture(TileDrawStep.java:286)
	at journeymap.client.render.map.TileDrawStep.<init>(TileDrawStep.java:80)
	at journeymap.client.render.map.TileDrawStepCache._getOrCreate(TileDrawStepCache.java:88)
	at journeymap.client.render.map.TileDrawStepCache.getOrCreate(TileDrawStepCache.java:57)
	at journeymap.client.io.RegionImageHandler.getTileDrawSteps(RegionImageHandler.java:362)
	at journeymap.client.render.map.Tile.updateTexture(Tile.java:125)
	at journeymap.client.render.map.Tile.create(Tile.java:67)
	at journeymap.client.render.map.GridRenderer.findTile(GridRenderer.java:711)
	at journeymap.client.render.map.GridRenderer.center(GridRenderer.java:239)
	at journeymap.client.ui.minimap.MiniMap.initGridRenderer(MiniMap.java:133)
	at journeymap.client.ui.minimap.MiniMap.reset(MiniMap.java:665)
	at journeymap.client.JourneymapClient.reset(JourneymapClient.java:619)
	at journeymap.client.JourneymapClient.startMapping(JourneymapClient.java:525)
	at journeymap.client.task.main.MappingMonitorTask.perform(MappingMonitorTask.java:72)
	at journeymap.client.task.main.MainTaskController.performTasks(MainTaskController.java:84)
	at journeymap.client.JourneymapClient.performMainThreadTasks(JourneymapClient.java:639)
	at journeymap.client.forge.event.StateTickHandler.onClientTick(StateTickHandler.java:73)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_557_StateTickHandler_onClientTick_ClientTickEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraftforge.fml.common.FMLCommonHandler.onPreClientTick(FMLCommonHandler.java:344)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1708)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1098)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:3942)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
```

Journey map couldn't allocate a block of memory and throws an OutOfMemoryError.
Prior to that: 
```
[10:53:31] [Client thread/ERROR] [net.minecraft.client.Minecraft]: ########## GL ERROR ##########
[10:53:31] [Client thread/ERROR] [net.minecraft.client.Minecraft]: @ Post render
[10:53:31] [Client thread/ERROR] [net.minecraft.client.Minecraft]: 1285: Out of memory
```
OpenGL throws Out Of Memory errors.
2 Things are happening here, firstly you are running out of video memory, secondly you are running out of system memory. Due to the fact that you are running integrated graphics and 32 bit windows, i recomend upgrading to a 64bit operating system, and allocate more memory to your minecraft instance.

Regardless, this is not a MixinBootstrap issue.

**Comment by LXGaming** [comment]
What covers said.

**Comment by Craft1s** [comment]
OK, i'll do your advice.

**Comment by Craft1s** [comment]
I replicated the error and I also checked my system.
[crash-2020-09-08_13.44.52-client.txt](https://github.com/LXGaming/MixinBootstrap/files/5186346/crash-2020-09-08_13.44.52-client.txt)
[crash-2020-09-08_13.44.57-client.txt](https://github.com/LXGaming/MixinBootstrap/files/5186348/crash-2020-09-08_13.44.57-client.txt)

![system](https://user-images.githubusercontent.com/70912045/92438227-027b7a80-f1db-11ea-8f89-1043acd6c7bd.jpg)
![memory](https://user-images.githubusercontent.com/70912045/92438249-09a28880-f1db-11ea-86cc-e76e2141250e.jpg)

**Comment by covers1624** [comment]
If you wish to receive more help, activate your windows. Alternatively, install Linux.
