### ISSUE TITLE
[1.15.2]Server error message

### ISSUE THREAD

**Issue by EnterFor** [LXGaming/MixinBootstrap#7]
![image](https://user-images.githubusercontent.com/10114685/76823122-2a9ea800-684e-11ea-86ea-2077359033fe.png)

I don't know if this Mod caused it.
So let me ask

Forge：31.1.18
Mod：1.0.2

**Comment by LXGaming** [comment]
Can you please upload the `debug.log` file

**Comment by EnterFor** [comment]
[debug.log](https://github.com/LXGaming/MixinBootstrap/files/4341540/debug.log)

**Comment by qouteall** [comment]
It's probably not an issue of MixinBootstrap

**Comment by LXGaming** [comment]
The method throwing this error is called `writeStructures`, It's most likely an issue with a mod that's adding custom structures incorrectly

**Comment by EnterFor** [comment]
Is that the problem with the Minecolonies?

I don't really understand the code,
What should I do now?
I am a Chinese, maybe there is something wrong with the way of expression, sorry

This is the latest debug
`[17三月2020 13:22:31.203] [Server thread/INFO] [net.minecraft.server.dedicated.DedicatedServer/]: <xiao_xing> 这个 不用输密码的嘛 ？？
[17三月2020 13:23:32.692] [Server thread/ERROR] [net.minecraft.world.server.ChunkManager/]: Couldn't load chunk [60, 36]
java.lang.ArrayIndexOutOfBoundsException: 17
	at net.minecraft.util.palette.PalettedContainer.md8f3db3$lambda$count$0$0(PalettedContainer.java:1142) ~[?:?]
	at net.minecraft.util.BitArray.func_225421_a(SourceFile:126) ~[?:?]
	at net.minecraft.util.palette.PalettedContainer.handler$zzk000$count(PalettedContainer.java:1142) ~[?:?]
	at net.minecraft.util.palette.PalettedContainer.func_225497_a(PalettedContainer.java) ~[?:?]
	at net.minecraft.world.chunk.ChunkSection.func_76672_e(SourceFile:121) ~[?:?]
	at net.minecraft.world.chunk.storage.ChunkSerializer.func_222656_a(ChunkSerializer.java:94) ~[?:?]
	at net.minecraft.world.server.ChunkManager.lambda$func_223172_f$14(ChunkManager.java:485) ~[?:?]
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(Unknown Source) [?:1.8.0_211]
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213166_h(SourceFile:144) [?:?]
	at net.minecraft.world.server.ServerChunkProvider$ChunkExecutor.func_213166_h(SourceFile:551) [?:?]
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213168_p(SourceFile:118) [?:?]
	at net.minecraft.world.server.ServerChunkProvider$ChunkExecutor.func_213168_p(SourceFile:560) [?:?]
	at net.minecraft.world.server.ServerChunkProvider.func_217234_d(SourceFile:278) [?:?]
	at net.minecraft.server.MinecraftServer.func_213205_aW(MinecraftServer.java:719) [?:?]
	at net.minecraft.server.MinecraftServer.func_213168_p(MinecraftServer.java:708) [?:?]
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213160_bf(SourceFile:103) [?:?]
	at net.minecraft.server.MinecraftServer.func_213202_o(MinecraftServer.java:693) [?:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:641) [?:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_211]
[17三月2020 13:25:11.034] [Server thread/DEBUG] [net.minecraftforge.fml.FMLWorldPersistenceHook/WP]: Gathering id map for writing to world save world`
