### ISSUE TITLE
[1.14.4] Game crashing on startup with no error message.

### ISSUE THREAD

**Issue by ghost** [LXGaming/MixinBootstrap#8]
I was told to post my debug log so here it is.
[19:18:41] [main/INFO]: ModLauncher 3.2.0+60+b86c1d4 starting: java version 1.8.0_51 by Oracle Corporation
[19:18:42] [main/INFO]: OptiFineTransformationService.onLoad
[19:18:42] [main/INFO]: OptiFine ZIP file: C:\Users\Conno\Twitch\Minecraft\Instances\yeet\mods\OptiFine_1.14.4_HD_U_F5.jar
[19:18:42] [main/INFO]: Added Lets Encrypt root certificates as additional trust
[19:18:42] [main/INFO]: OptiFineTransformationService.initialize
[19:18:42] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: org.spongepowered.asm.service.ServiceNotAvailableError: No mixin host service is available. Services: INVALID[ModLauncher] and 1 other invalid services.
[19:18:42] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at org.spongepowered.asm.service.MixinService.initService(MixinService.java:159)
[19:18:42] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at org.spongepowered.asm.service.MixinService.getServiceInstance(MixinService.java:125)
[19:18:42] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at org.spongepowered.asm.service.MixinService.getService(MixinService.java:120)
[19:18:42] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at org.spongepowered.asm.launch.MixinBootstrap.<clinit>(MixinBootstrap.java:78)
[19:18:42] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at org.spongepowered.asm.launch.MixinTransformationService.initialize(MixinTransformationService.java:84)
[19:18:42] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at io.github.lxgaming.mixin.launch.MixinTransformationService.lambda$initialize$2(MixinTransformationService.java:81)
[19:18:42] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at io.github.lxgaming.mixin.launch.MixinTransformationService$$Lambda$143/1631086936.accept(Unknown Source)
[19:18:42] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at java.lang.Iterable.forEach(Iterable.java:75)
[19:18:42] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at io.github.lxgaming.mixin.launch.MixinTransformationService.initialize(MixinTransformationService.java:81)
[19:18:42] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at cpw.mods.modlauncher.TransformationServiceDecorator.onInitialize(TransformationServiceDecorator.java:67)
[19:18:42] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at cpw.mods.modlauncher.TransformationServicesHandler.lambda$initialiseTransformationServices$7(TransformationServicesHandler.java:106)
[19:18:42] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at cpw.mods.modlauncher.TransformationServicesHandler$$Lambda$85/1069716895.accept(Unknown Source)
[19:18:42] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at java.util.HashMap$Values.forEach(HashMap.java:972)
[19:18:42] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at cpw.mods.modlauncher.TransformationServicesHandler.initialiseTransformationServices(TransformationServicesHandler.java:106)
[19:18:42] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at cpw.mods.modlauncher.TransformationServicesHandler.initializeTransformationServices(TransformationServicesHandler.java:59)
[19:18:42] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at cpw.mods.modlauncher.Launcher.run(Launcher.java:75)
[19:18:42] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at cpw.mods.modlauncher.Launcher.main(Launcher.java:65)

**Comment by LXGaming** [comment]
Update Forge.
Mixin requires ModLauncher v4.1 or higher which is only available in Forge 28.1.45 and above

**Comment by ghost** [comment]
> Update Forge.
> Mixin requires ModLauncher v4.1 or higher which is only available in Forge 28.1.45 and above

I did what you said, but this happened.

java.lang.NullPointerException: Rendering overlay
	at net.minecraft.client.renderer.FluidBlockRenderer.func_178268_a(FluidBlockRenderer.java:41) ~[?:?] {re:classloading,xf:OptiFine:default}
	at net.minecraft.client.renderer.BlockRendererDispatcher.func_195410_a(BlockRendererDispatcher.java:154) ~[?:?] {re:classloading,xf:OptiFine:default}
	at net.minecraft.resources.IResourceManagerReloadListener.lambda$reload$0(IResourceManagerReloadListener.java:16) ~[?:?] {re:classloading,re:mixin}
	at net.minecraft.resources.IResourceManagerReloadListener$$Lambda$2569/210282562.run(Unknown Source) ~[?:?] {}
	at java.util.concurrent.CompletableFuture.uniRun(CompletableFuture.java:705) ~[?:1.8.0_51] {}
	at java.util.concurrent.CompletableFuture$UniRun.tryFire(CompletableFuture.java:687) ~[?:1.8.0_51] {}
	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:442) ~[?:1.8.0_51] {}
	at net.minecraft.resources.AsyncReloader.func_219557_a(SourceFile:71) ~[?:?] {re:classloading}
	at net.minecraft.resources.AsyncReloader$$Lambda$2808/2114020759.run(Unknown Source) ~[?:?] {}
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213166_h(ThreadTaskExecutor.java:170) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,xf:OptiFine:default}
	at net.minecraft.util.concurrent.RecursiveEventLoop.func_213166_h(SourceFile:23) ~[?:?] {re:mixin,re:classloading}
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213168_p(ThreadTaskExecutor.java:135) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,xf:OptiFine:default}
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213160_bf(ThreadTaskExecutor.java:115) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,xf:OptiFine:default}
	at net.minecraft.client.Minecraft.func_195542_b(Minecraft.java:861) [?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:384) [?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(SourceFile:155) [?:?] {re:classloading}
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51] {}
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51] {}
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:56) [forge-1.14.4-28.2.3.jar:28.2] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$460/1275011461.call(Unknown Source) [forge-1.14.4-28.2.3.jar:28.2] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-4.1.0.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-4.1.0.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-4.1.0.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:81) [modlauncher-4.1.0.jar:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:65) [modlauncher-4.1.0.jar:?] {}

**Comment by LXGaming** [comment]
Try recommended Forge (28.2.0) as mentioned here https://github.com/sp614x/optifine/issues/3490

**Comment by ghost** [comment]
I am trying 28.2.3 though...

**Comment by LXGaming** [comment]
According to the issue I linked OptiFine isn't compatible with Forge 28.2.3, Hence why I said to downgrade to Forge 28.2.0 cause that version should be compatible with MixinBootstrap and OptiFine

**Comment by LXGaming** [comment]
I'm assuming the issue has been resolved, If not then reply in this thread.
